# -*- coding: utf-8 -*-
"""ML-based Material Selection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aq_ZPOLYYzPO8RJrXGO0kGwqCb1ZYtyL
"""

!pip uninstall cupy-cuda11x cupy-cuda12x cuml-cu12 cudf-cu12 rmm-cu12 \
    pylibraft-cu12 cuvs-cu12 libcuml-cu12 libcudf-cu12 librmm-cu12 \
    pylibcudf-cu12 -y --quiet
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!python rapidsai-csp-utils/colab/pip-install.py

# ── GPU/CPU Import Block ──────────────────────────────────────────
import warnings
warnings.filterwarnings('ignore')

try:
    import cuml
    from cuml.cluster import KMeans
    from cuml.decomposition import PCA
    from cuml.manifold import TSNE
    from cuml.preprocessing import StandardScaler
    USE_GPU = True
    print(f"✓ GPU mode — cuML {cuml.__version__}")
    !nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
except ImportError:
    from sklearn.cluster import KMeans
    from sklearn.decomposition import PCA
    from sklearn.manifold import TSNE
    from sklearn.preprocessing import StandardScaler
    USE_GPU = False
    print("⚠ CPU mode — cuML not found, falling back to sklearn")

import pandas as pd
import numpy as np
from google.colab import files

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

plt.style.use('seaborn-v0_8')
sns.set_palette("husl")
from IPython.display import display

uploaded = files.upload()

df = pd.read_csv("Data.csv", encoding='latin1')

df.columns = df.columns.str.strip().str.replace('\x92', "'").str.lower()

df.replace(["NaN", "nan", "NULL", ""], np.nan, inplace=True)
df[df.select_dtypes(include=['number']).columns] = (
    df.select_dtypes(include=['number'])
    .fillna(df.median(numeric_only=True))
)

df.info()
df.head()

X = df.select_dtypes(include=['float64','int64']).drop(columns=['cluster'], errors='ignore')

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X).astype('float32')

import pandas as pd

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled_df.head()

inertia = []
K_range = range(2, 10)

for k in K_range:
    kwargs = dict(n_clusters=k, random_state=42, max_iter=300)
    if not USE_GPU:
        kwargs['n_init'] = 10
    kmeans = KMeans(**kwargs)
    kmeans.fit(X_scaled)
    inertia.append(float(kmeans.inertia_))

plt.figure(figsize=(6,4))
plt.plot(K_range, inertia, marker='o')
plt.xlabel("Number of clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method to find Optimal K")
plt.show()

import joblib

kwargs = dict(n_clusters=3, random_state=42, max_iter=300)
if not USE_GPU:
    kwargs['n_init'] = 10
kmeans = KMeans(**kwargs)
clusters = kmeans.fit_predict(X_scaled)

df['cluster'] = clusters.astype(int)

joblib.dump(kmeans, 'kmeans_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

pca = PCA(n_components=2)
X_pca = np.array(pca.fit_transform(X_scaled))

print(f"Variance explained by PC1+PC2: {pca.explained_variance_ratio_.sum()*100:.1f}%")

plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=df['cluster'], palette='Set1', s=100)
plt.title("Material Clusters (2D PCA)")
plt.xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
plt.ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
plt.show()

X_tsne = np.array(TSNE(n_components=2, perplexity=30).fit_transform(X_scaled))

plt.figure(figsize=(8,6))
sns.scatterplot(x=X_tsne[:,0], y=X_tsne[:,1], hue=df['cluster'], palette='Set1', s=100)
plt.title("Material Clusters (2D t-SNE)")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.show()

pca3d = PCA(n_components=3)
X_pca3d = np.array(pca3d.fit_transform(X_scaled))

print(f"Variance explained by PC1+PC2+PC3: {pca3d.explained_variance_ratio_.sum()*100:.1f}%")

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(X_pca3d[:,0], X_pca3d[:,1], X_pca3d[:,2],
           c=df['cluster'], cmap='Set1', s=50)
ax.set_xlabel(f"PC1 ({pca3d.explained_variance_ratio_[0]*100:.1f}%)")
ax.set_ylabel(f"PC2 ({pca3d.explained_variance_ratio_[1]*100:.1f}%)")
ax.set_zlabel(f"PC3 ({pca3d.explained_variance_ratio_[2]*100:.1f}%)")
plt.title("Material Clusters (3D PCA)")
plt.show()

for i in sorted(df['cluster'].astype(int).unique().tolist()):
    print(f"\nCluster {i} materials:")
    print(df[df['cluster']==i]['material'].tolist())

cluster_to_component = {
    0: 'Lightweight parts',
    1: 'Standard machinery',
    2: 'Engine / Turbine'
}
df['recommended_component'] = df['cluster'].astype(int).map(cluster_to_component)

for i in df['cluster'].unique():
    print(f"\nCluster {i} ({df[df['cluster']==i]['recommended_component'].unique()[0]}) materials:")
    print(df[df['cluster']==i]['material'].tolist())

numeric_df = df.select_dtypes(include=np.number).drop(columns=['cluster'], errors='ignore')
cluster_summary = numeric_df.groupby(df['cluster'].astype(int)).mean()

deduped = df.drop_duplicates('cluster')[['cluster', 'recommended_component']].copy()
deduped['cluster'] = deduped['cluster'].astype(int)
deduped = deduped.set_index('cluster')

cluster_summary['recommended_component'] = cluster_summary.index.map(
    deduped['recommended_component']
)

print(cluster_summary)

material_lists = []
for cluster_id in sorted(cluster_summary.index.astype(int).tolist()):
    materials = df[df['cluster'].astype(int) == cluster_id]['material'].tolist()
    material_lists.append(materials)

cluster_summary['materials'] = material_lists

numeric_cols = [c for c in cluster_summary.columns
                if c not in ['recommended_component', 'materials']]

cluster_summary = cluster_summary[['recommended_component', 'materials'] + numeric_cols]

display(cluster_summary)

cluster_summary.to_csv("Cluster_Summary.csv", index=True)

def recommend_materials_for_component(component):
    rows = cluster_summary[cluster_summary['recommended_component'] == component]
    if rows.empty:
        print(f"'{component}' not found. Options: {cluster_summary['recommended_component'].tolist()}")
        return None
    if len(rows) > 1:
        print(f"Warning: multiple clusters matched '{component}', returning first.")
    return rows['materials'].values[0]

# Mapping for short codes
component_mapping = {
    'Lp': 'Lightweight parts',
    'Sm': 'Standard machinery',
    'Et': 'Engine / Turbine'
}

# Function: recommend materials for a component
def recommend_material_by_component(component_name):
    if component_name in component_mapping:
        component_name = component_mapping[component_name]

    if component_name not in cluster_summary['recommended_component'].values:
        print("Component not found. Use full name or short codes: Lp, Sm, Et.")
        print(f"Available: {cluster_summary['recommended_component'].tolist()}")
        return

    materials = cluster_summary.loc[
        cluster_summary['recommended_component'] == component_name, 'materials'
    ].values[0]
    cluster_info = cluster_summary[cluster_summary['recommended_component'] == component_name].iloc[0]
    short_code = [k for k,v in component_mapping.items() if v == component_name][0]

    print(f"\nComponent: {component_name} ({short_code})")
    print("Recommended materials and reasons:\n")

    for mat in materials:
        matches = df[df['material'] == mat]
        if matches.empty:
            print(f"Material: {mat} — not found in dataset, skipping.")
            continue
        mat_row = matches.iloc[0]
        reasons = []

        if 'ultimate tensile strength' in df.columns and pd.notna(mat_row['ultimate tensile strength']) and mat_row['ultimate tensile strength'] >= cluster_info['ultimate tensile strength']:
            reasons.append(f"High tensile strength ({mat_row['ultimate tensile strength']:.2f})")
        if 'yield strength' in df.columns and pd.notna(mat_row['yield strength']) and mat_row['yield strength'] >= cluster_info['yield strength']:
            reasons.append(f"High yield strength ({mat_row['yield strength']:.2f})")
        if 'brinell hardness number' in df.columns and pd.notna(mat_row['brinell hardness number']) and mat_row['brinell hardness number'] >= cluster_info['brinell hardness number']:
            reasons.append(f"High hardness ({mat_row['brinell hardness number']:.2f}) → wear-resistant")
        if "young's modulus" in df.columns and pd.notna(mat_row["young's modulus"]) and mat_row["young's modulus"] >= cluster_info["young's modulus"]:
            ym = mat_row["young's modulus"]
            reasons.append(f"High stiffness ({ym:.2f}) → maintains shape under load")
        if 'density' in df.columns and pd.notna(mat_row['density']) and mat_row['density'] <= cluster_info['density']:
            reasons.append(f"Density ({mat_row['density']:.2f}) suitable for weight requirements")
        if not reasons:
            reasons.append("Properties generally match component requirements")

        print(f"Material: {mat}")
        print("Reasons:", "; ".join(reasons))
        print("-" * 75)


# Function: recommend component for a material
def recommend_component_by_material(material_input):
    found = df[df['material'].str.contains(material_input, case=False, na=False)]
    if found.empty:
        print(f"Material '{material_input}' not found in dataset.")
        print("Try a partial name e.g. 'Steel', 'Brass', 'Aluminum'")
        return

    for comp, group in found.groupby('recommended_component'):
        matching_codes = [k for k,v in component_mapping.items() if v == comp]
        short_code = matching_codes[0] if matching_codes else '??'
        cluster_info = cluster_summary[cluster_summary['recommended_component'] == comp].iloc[0]

        print(f"\nMaterial type input: {material_input}")
        print(f"Recommended component: {comp} ({short_code})")
        print(f"Number of matching alloys: {len(group)}")

        reasons = []
        for col, label in [
            ('ultimate tensile strength', 'High avg tensile strength'),
            ('yield strength',            'High avg yield strength'),
            ('brinell hardness number',   'Avg hardness'),
            ("young's modulus",           'Avg stiffness'),
            ('density',                   'Avg density'),
        ]:
            if col in cluster_info.index and pd.notna(cluster_info[col]) and cluster_info[col] > 0:
                reasons.append(f"{label} ({cluster_info[col]:.2f})")

        print("Reasons why this component suits the material group:")
        for r in reasons:
            print(r)

        print("\nSample alloys in this group and key properties:")
        for _, row in group.head(5).iterrows():
            print(f"  Material: {row['material']}")
            for col in ['ultimate tensile strength', 'yield strength',
                        'brinell hardness number', "young's modulus", 'density']:
                if col in row.index and pd.notna(row[col]):
                    print(f"    - {col.title()}: {row[col]}")
            print("-" * 50)
        if len(group) > 5:
            print(f"...and {len(group)-5} more alloys in this group.")
        print("=" * 75)


# Interactive widget
import ipywidgets as widgets
from IPython.display import display

mode = widgets.ToggleButtons(
    options=[('Component → Materials', '1'), ('Material → Component', '2')],
    description='Mode:'
)
query = widgets.Text(placeholder='Type here...', description='Search:')
button = widgets.Button(description='Run', button_style='primary')
output = widgets.Output()

def on_click(b):
    output.clear_output()
    with output:
        if not query.value.strip():
            print("Please enter a search term.")
            return
        if mode.value == '1':
            recommend_material_by_component(query.value.strip())
        else:
            recommend_component_by_material(query.value.strip())

button.on_click(on_click)
display(mode, query, button, output)

gitignore_content = """# Python
__pycache__/
*.py[cod]
*.egg-info/
.env
venv/
.venv/

# Jupyter
.ipynb_checkpoints/
*.ipynb_checkpoints

# Data (if large)
*.csv
*.xlsx
*.zip
*.h5
*.pkl

# Model weights
*.pt
*.pth
*.ckpt

# OS
.DS_Store
Thumbs.db
"""

with open('.gitignore', 'w') as f:
    f.write(gitignore_content)

print("Done! .gitignore created.")

!pip freeze > requirements.txt